#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Specify config id."
    exit
else
    ID=$1
fi

SELECT="SELECT json FROM configs WHERE id='ID';"
INSERT="INSERT INTO configs VALUES('ID', 'JSON');"
UPDATE="UPDATE configs SET json='JSON' WHERE id='ID';"
#DELETE="DELETE FROM configs WHERE id='ID';"

source /etc/jconfig/config

INPUT=`echo ${SELECT/ID/$ID} | mysql $DB -h $HOST -u $USER -p$PASSWORD --silent`
TMP=$RANDOM
jq '.' <(echo $INPUT) > $TMP

vim $TMP

diff <(echo $INPUT) <(jq -c '.' $TMP) > /dev/null
if [ $? -eq 1 ]; then
    JSON=`jq -c '.' $TMP` 
    if [ "$JSON" = "" ]; then
        echo "Invalid input, aborting."
        exit
    elif [ "$INPUT" = "" ]; then
        COMMAND=$INSERT
        MSG="$ID inserted."
    else
        COMMAND=$UPDATE
        MSG="$ID updated."
    fi
    COMMAND=${COMMAND/ID/$ID}
    COMMAND=${COMMAND/JSON/$JSON}
    echo $COMMAND | mysql $DB -h $HOST -u $USER -p$PASSWORD --silent
    if [ $? -eq 0 ]; then
        echo $MSG
    fi
else
    echo "$ID not modified."
fi

rm $TMP

